import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, CheckCircle2, Clock3, Video } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Reveal } from "@/components/Reveal";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

type BookingData = { name: string; email: string; service: string; date: string; time: string; budget: string; note: string; createdAt: string };

export const Route = createFileRoute("/booking")({ head: () => ({ meta: [{ title: "Book a Consultation | Taiwo Emmanuel" }, { name: "description", content: "Book a website project consultation with Taiwo Emmanuel." }] }), component: Booking });

function Booking() {
  const [booking, setBooking] = useState<BookingData | null>(null);
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const data = Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string, string>;
    const saved: BookingData = { name: data.name || "", email: data.email || "", service: data.service || "", date: data.date || "", time: data.time || "", budget: data.budget || "", note: data.note || "", createdAt: new Date().toISOString() };
    localStorage.setItem("taiwo-booking", JSON.stringify(saved));
    setBooking(saved);
  }
  function resetBooking() { localStorage.removeItem("taiwo-booking"); setBooking(null); }
  return <div className="min-h-screen bg-background text-foreground"><SiteHeader/><main className="px-5 pb-20 pt-32 md:pt-40"><div className="mx-auto max-w-6xl"><Reveal><p className="text-sm font-medium uppercase tracking-wide text-primary">Book a consultation</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Let’s Talk About Your Project</h1><p className="mt-4 max-w-2xl text-muted-foreground">Choose a preferred time and share a few details. Your request is saved in this browser without requiring an API, account or third-party booking service.</p></Reveal><div className="mt-12 grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><Reveal><div className="space-y-4"><Info icon={<CalendarDays/>} title="Flexible consultation" text="Choose the date and time that works best for you."/><Info icon={<Clock3/>} title="30-minute session" text="A focused conversation about your goals, scope and next steps."/><Info icon={<Video/>} title="Remote-friendly" text="The consultation can be arranged online."/><a href="/contact" className="block rounded-2xl border border-border bg-card/50 p-5 text-sm hover:border-primary/50"><span className="font-semibold">Prefer a written enquiry?</span><span className="mt-1 block text-muted-foreground">Use the full contact form instead.</span></a></div></Reveal><Reveal delay={100}><div className="rounded-3xl border border-border bg-card/60 p-6 sm:p-8">{booking ? <Confirmation booking={booking} onReset={resetBooking}/> : <form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" name="name" required/><Field label="Email" name="email" type="email" required/></div><div className="mt-4"><Select label="Service" name="service" options={["Website Design","Website Development","Business Website","UI/UX Optimisation","E-commerce Website","Website Redesign"]}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Preferred date" name="date" type="date" required/><Field label="Preferred time" name="time" type="time" required/></div><div className="mt-4"><Select label="Budget" name="budget" options={["$850 – $1,000","$1,000 – $2,500","$2,500 – $5,000","$5,000+"]}/></div><label className="mt-4 block text-sm font-medium">Project details<textarea name="note" rows={5} maxLength={1500} placeholder="Briefly tell me what you want to build..." className="mt-2 w-full resize-none rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary"/></label><button type="submit" className="mt-6 inline-flex items-center justify-center rounded-full px-6 py-3 text-sm font-semibold text-primary-foreground" style={{background:"var(--gradient-primary)"}}>Save booking request</button></form>}</div></Reveal></div></div></main><SiteFooter/></div>;
}
function Confirmation({booking,onReset}:{booking:BookingData;onReset:()=>void}) { return <div className="py-4"><CheckCircle2 className="size-14 text-primary"/><h2 className="mt-5 text-2xl font-bold">Booking request received</h2><p className="mt-3 text-sm text-muted-foreground">Thank you for sharing your project details. Your request has been saved successfully on this device. No email has been sent automatically.</p><div className="mt-6 rounded-2xl border border-border bg-background/60 p-5"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Item label="Name" value={booking.name}/><Item label="Email" value={booking.email}/><Item label="Service" value={booking.service}/><Item label="Preferred date" value={booking.date}/><Item label="Preferred time" value={booking.time}/><Item label="Budget" value={booking.budget}/></dl>{booking.note&&<div className="mt-4 border-t border-border pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Project details</p><p className="mt-2 whitespace-pre-wrap text-sm">{booking.note}</p></div>}</div><div className="mt-6 flex flex-wrap gap-3"><a href="/" className="rounded-full px-5 py-2.5 text-sm font-semibold text-primary-foreground" style={{background:"var(--gradient-primary)"}}>Return Home</a><a href="/services" className="rounded-full border border-border px-5 py-2.5 text-sm font-semibold">View Services</a><button type="button" onClick={onReset} className="rounded-full border border-border px-5 py-2.5 text-sm font-semibold">Submit another booking</button></div></div> }
function Item({label,value}:{label:string;value:string}) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium break-words">{value}</dd></div> }
function Field({ label, name, type="text", required=false }: {label:string;name:string;type?:string;required?:boolean}) { return <label className="block text-sm font-medium">{label}{required&&<span> *</span>}<input name={name} type={type} required={required} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary"/></label>; }
function Select({label,name,options}:{label:string;name:string;options:string[]}) { return <label className="block text-sm font-medium">{label}<select name={name} required defaultValue="" className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary"><option value="" disabled>Select {label.toLowerCase()}</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>; }
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div className="flex gap-4 rounded-2xl border border-border bg-card/50 p-5"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-primary/10 text-primary">{icon}</div><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{text}</p></div></div>; }
