import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckSquare, Gauge, LayoutList, ShoppingBag } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { Reveal } from "@/components/Reveal";

const RESOURCES = [
  { title: "Business Website Planning Checklist", category: "Website Planning", description: "A practical starting list for defining goals, audiences, pages, content and calls to action.", icon: LayoutList, items: ["Define the primary business goal", "Identify key visitor groups", "List essential pages and actions", "Prepare content and brand assets"] },
  { title: "Website Launch Checklist", category: "Launch", description: "A final review list for links, forms, responsive layouts, metadata and production readiness.", icon: CheckSquare, items: ["Test navigation and forms", "Check mobile, tablet and desktop layouts", "Review titles, descriptions and image alt text", "Confirm production environment variables"] },
  { title: "Website Performance Starter Guide", category: "Performance", description: "Simple areas to review before reaching for complex optimisation techniques.", icon: Gauge, items: ["Resize and optimise images", "Remove unnecessary scripts", "Check loading behaviour", "Measure and verify improvements"] },
  { title: "E-commerce UX Starter Guide", category: "E-commerce", description: "A compact framework for making product discovery and purchase decisions easier to navigate.", icon: ShoppingBag, items: ["Clarify product information", "Keep filters understandable", "Make purchase actions obvious", "Explain delivery and returns clearly"] },
];

export const Route = createFileRoute("/resources")({ head: () => ({ meta: [{ title: "Resources | Taiwo Emmanuel" }, { name: "description", content: "Website planning, launch, UX, performance and e-commerce resources from Taiwo Emmanuel." }] }), component: ResourcesPage });

function ResourcesPage() { return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="px-5 pb-20 pt-32 md:pt-40"><div className="mx-auto max-w-6xl"><Reveal><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Resources</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">Practical resources for better websites.</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground">Useful checklists and guides for planning, launching and improving a business website.</p></Reveal><div className="mt-12 grid gap-5 md:grid-cols-2">{RESOURCES.map((resource, i) => <Reveal key={resource.title} delay={i * 70}><article className="rounded-2xl border border-border bg-card/60 p-6"><resource.icon className="size-6 text-primary" /><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{resource.category}</p><h2 className="mt-2 text-xl font-semibold">{resource.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{resource.description}</p><ul className="mt-5 space-y-2 text-sm text-muted-foreground">{resource.items.map(item => <li key={item}>• {item}</li>)}</ul></article></Reveal>)}</div><Link to="/contact" className="mt-10 inline-flex items-center gap-2 rounded-full px-6 py-3 text-sm font-semibold text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>Start a Project <ArrowRight className="size-4" /></Link></div></main><SiteFooter /></div>; }
