import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Portfolio3DVisual } from "@/components/Portfolio3DVisual";
import { Reveal } from "@/components/Reveal";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
const PROJECTS=[
 ["meridian-consulting","meridian","Meridian Consulting","Business Website","A multi-page site for a consulting practice with service breakdowns, case summaries and a booking-first contact flow.",["5 pages","Responsive","Lead form"]],
 ["lumen-studio","lumen","Lumen Studio","Landing Page","A single-scroll launch page built around one offer, with sectioned proof, pricing clarity and a persistent call to action.",["One-page","Animation","CTA focus"]],
 ["northside-fitness","northside","Northside Fitness","Redesign","Rebuild of a dated gym site: new visual system, simplified class schedule and a mobile-first membership sign-up path.",["Redesign","Mobile-first","Schedule UI"]],
 ["crate-and-co","crate","Crate & Co.","E-commerce UI","Storefront interface work covering product grids, filtering and a streamlined checkout layout designed to reduce drop-off.",["Catalogue","Filters","Checkout"]],
 ["atlas-dashboard","atlas","Atlas Dashboard","UI/UX","An admin interface concept with dense data tables, clear states and a component set that scales across screen sizes.",["Design system","Data tables","Dark mode"]],
 ["verde-interiors","verde","Verde Interiors","Portfolio","A gallery-led portfolio for an interior design practice, prioritising imagery, whitespace and quiet, confident navigation.",["Gallery","Typography","Enquiries"]],
] as const;
export const Route=createFileRoute("/projects/")({head:()=>({meta:[{title:"Projects | Taiwo Emmanuel"},{name:"description",content:"Selected web design and development projects by Taiwo Emmanuel."}]}),component:Projects});
function Projects(){return <div className="min-h-screen bg-background text-foreground"><SiteHeader/><main className="px-5 pb-20 pt-32 md:pt-40"><div className="mx-auto max-w-6xl"><Reveal><p className="text-sm font-medium uppercase tracking-wide text-primary">Taiwo Emmanuel</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Selected projects</h1><p className="mt-4 max-w-xl text-muted-foreground">A cross-section of the kind of work already represented in this portfolio.</p></Reveal><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{PROJECTS.map(([slug,visual,name,tag,body,detail],i)=><Reveal key={slug} delay={(i%3)*70} as="article"><article className="flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-card/60"><Portfolio3DVisual kind="project" project={visual} className="min-h-40 rounded-none border-0 border-b"/><div className="flex flex-1 flex-col p-6"><span className="text-xs font-medium text-primary">{tag}</span><h2 className="mt-2 text-lg font-semibold">{name}</h2><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{body}</p><div className="mt-5 flex flex-wrap gap-2">{detail.map(d=><span key={d} className="rounded-md border border-border px-2 py-1 text-[11px] text-muted-foreground">{d}</span>)}</div><a href={`/projects/${slug}`} className="mt-5 inline-flex w-fit items-center gap-2 text-sm font-semibold text-primary hover:underline">Case Study <ArrowRight className="size-4"/></a></div></article></Reveal>)}</div></div></main><SiteFooter/></div>}
