import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Clock3 } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { Reveal } from "@/components/Reveal";
import { ARTICLES } from "@/routes/insights";

const CONTENT: Record<string, { intro: string; sections: { heading: string; body: string; bullets?: string[] }[] }> = {
  "what-makes-a-business-website-actually-work": { intro: "Your website should do more than look polished. It should give the right visitor confidence, answer the questions holding them back and make the next step feel natural. When every page has a purpose, your website becomes an active part of growing the business.", sections: [{ heading: "Begin with the outcome that matters", body: "Before choosing colours or layouts, decide what success looks like. It might be more qualified enquiries, stronger credibility or a clearer way to explain a valuable service. One meaningful goal gives every page, message and interaction a direction." }, { heading: "Win clarity in the first few seconds", body: "People should not have to decode what a business does. A focused opening message can reassure visitors that they are in the right place and give them a compelling reason to continue.", bullets: ["Describe the offer in clear, confident language.", "Show who the service is for and why it matters.", "Make the primary next step easy to recognise.", "Use meaningful headings that reward people who scan."] }, { heading: "Turn attention into confidence", body: "Visitors move forward when uncertainty disappears. Useful service details, relevant examples, an honest process and clear expectations provide the evidence they need to make a decision. Great design brings those signals together without overwhelming the page." }, { heading: "Design every page around a decision", body: "Each page should help someone answer a question: Is this right for me? Can I trust this business? What happens next? When content follows that journey, calls to action feel helpful rather than pushy—and more visitors are ready to act." }, { heading: "Build a website that keeps earning", body: "The strongest websites improve with the business. Reusable content, fast performance and straightforward editing make it easier to keep information current, learn from visitor behaviour and strengthen results over time." }, { heading: "A better website starts with purpose", body: "You do not need more decoration or more pages. You need a clear message, useful proof and a frictionless path forward. Get those fundamentals right, and your website can become one of the most persuasive conversations your business has every day." }] },
  "5-website-design-mistakes-that-cost-businesses-customers": { intro: "Small design decisions can create large amounts of friction. These problems often look harmless in isolation but become obvious when someone tries to complete a task.", sections: [{ heading: "1. Vague messaging", body: "If the headline could describe almost any business, visitors have to work too hard to understand the offer. Replace generic claims with a specific explanation of what you provide and who it is for." }, { heading: "2. Too many competing actions", body: "A page with several equally prominent buttons can make the visitor unsure where to go. Give each page a primary action and let secondary actions remain visually quieter." }, { heading: "3. Designing for a single screen", body: "A desktop composition can look excellent while becoming awkward on a phone. Responsive design should be considered from the beginning, especially for navigation, forms, spacing and content order." }, { heading: "4. Hiding important information", body: "Prices, service details, contact options or policies should not be unnecessarily difficult to locate. Good UX anticipates the questions a visitor is likely to have." }, { heading: "5. Treating trust as decoration", body: "Trust comes from consistency and useful evidence. Clear contact details, coherent branding, readable copy and accurate information often do more than decorative effects ever could." }] },
  "why-mobile-first-design-matters": { intro: "Mobile-first design is a way of prioritising content and interaction. Starting with limited screen space forces important decisions early, then the system can expand naturally for larger screens.", sections: [{ heading: "Start with what matters most", body: "A small screen exposes weak hierarchy quickly. Decide which content is essential, which can be secondary and which does not need to appear at all." }, { heading: "Design for touch", body: "Mobile interfaces need comfortable targets and simple interactions. Important controls should not depend on hover states, and forms should remain easy to complete with a thumb." }, { heading: "Let layouts grow", body: "As the viewport becomes wider, content can move into columns, gain breathing room and reveal supporting details. The larger layout should be an extension of the same system, not a separate design." }, { heading: "Test beyond the design file", body: "Responsive behaviour is part of development, so check real browser widths and content lengths. Look for wrapping headings, crowded buttons, unexpected overflow and difficult scrolling." }] },
  "website-speed-user-experience": { intro: "Speed is part of how a website feels. Visitors experience delays as uncertainty, interruption or friction even when they never inspect a performance report.", sections: [{ heading: "Start with the largest resources", body: "Images are often a practical first place to look. Use assets sized for their actual display area, choose appropriate formats and avoid shipping unnecessarily large files." }, { heading: "Keep the browser's work focused", body: "Every script and dependency has a cost. Remove unused code, avoid unnecessary libraries and defer work that is not needed for the first useful view." }, { heading: "Think about perceived performance", body: "A page can feel faster when important content appears quickly and the layout remains stable. Reserve image space, avoid sudden shifts and prioritise the content people came to see." }, { heading: "Measure, change, verify", body: "Performance should be iterative. Identify a concrete bottleneck, make a focused change and measure again rather than applying a long list of unverified optimisations." }] },
  "good-ui-ux-turns-visitors-into-customers": { intro: "Good UI/UX is not about adding more interface. It is about helping people understand, decide and act with less effort.", sections: [{ heading: "Clarity comes before cleverness", body: "Navigation labels, headings, buttons and forms should use language visitors understand. Familiar patterns reduce the amount of interpretation required." }, { heading: "Use hierarchy to guide attention", body: "Size, spacing, position and contrast can establish a reading order. When everything is visually loud, nothing has a clear priority." }, { heading: "Reduce friction at the point of action", body: "A good conversion path answers questions before asking for commitment. Keep forms focused, explain what happens after submission and make errors easy to recover from.", bullets: ["Ask only for information that is useful at that stage.", "Keep labels visible and specific.", "Give clear feedback after an action.", "Make the next step obvious."] }, { heading: "Design the whole journey", body: "UX includes what happens before and after a click. The destination page, confirmation state and follow-up experience all contribute to whether the journey feels trustworthy." }] },
  "before-building-a-business-website": { intro: "A smoother website project usually comes from making important decisions before development starts. Preparation does not mean having every detail solved; it means removing avoidable uncertainty.", sections: [{ heading: "Know the audience", body: "Describe the people the site is meant to help. Their needs, questions and level of familiarity should influence the language, structure and calls to action." }, { heading: "Prepare the content", body: "Gather service descriptions, business information, photography, brand assets and contact details early. Missing content is one of the easiest ways for a build to stall." }, { heading: "Agree on ownership", body: "Clarify who will provide feedback, who controls the domain and hosting, and who will maintain the website after launch. These practical details matter as much as the visual design." }, { heading: "Define success", body: "Choose a small set of meaningful outcomes such as enquiries, bookings, sales or clearer product information. This makes design decisions easier to evaluate." }] },
  "designing-websites-that-build-trust": { intro: "Trust is rarely created by one feature. It comes from many small signals agreeing with each other: clear information, consistent design, honest language and a predictable experience.", sections: [{ heading: "Be specific", body: "Specific descriptions are more useful than inflated claims. Explain what the business does, what visitors can expect and how the process works." }, { heading: "Keep the visual system consistent", body: "Typography, spacing, buttons, imagery and colour should feel like parts of one system. Consistency makes a website feel considered and easier to navigate." }, { heading: "Make contact information real", body: "A business asking visitors to trust it should make it straightforward to get in touch. Clear contact routes and useful response expectations reduce uncertainty." }, { heading: "Avoid trust-breaking details", body: "Broken links, placeholder copy, inconsistent names, outdated information and awkward mobile layouts can undermine otherwise strong work. Quality control is part of the brand experience." }] },
  "from-idea-to-launch-website-development-process": { intro: "My development process is structured to keep a website purposeful from the first conversation to the final launch. The exact workflow can adapt to the project, but the core stages remain clear.", sections: [{ heading: "1. Discovery", body: "Understand the business, audience, goals, existing assets and constraints. The aim is to know what the website needs to achieve before choosing implementation details." }, { heading: "2. Strategy and structure", body: "Plan the information architecture, page priorities, content hierarchy and key user journeys. This creates a foundation that the visual design can follow." }, { heading: "3. Design", body: "Develop the visual direction, typography, components and responsive layouts. Feedback is most useful here when it is tied to the project goals rather than personal preference alone." }, { heading: "4. Development", body: "Turn the approved structure and interface into a working website with responsive behaviour, accessible markup and purposeful interactions." }, { heading: "5. Testing", body: "Check routes, links, forms, responsive layouts, keyboard interactions, image loading and important states. Fix issues before launch rather than treating launch as the testing stage." }, { heading: "6. Launch", body: "Prepare the production build, verify the deployed experience and hand over the finished site clearly. A launch is the start of the website's useful life, not the end of its care." }] },
};

export const Route = createFileRoute("/insights/$slug")({
  loader: ({ params }) => { const article = ARTICLES.find((item) => item.slug === params.slug); const content = CONTENT[params.slug]; if (!article || !content) throw notFound(); return { article, content }; },
  head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.article.title ?? "Insight"} | Taiwo Emmanuel` }, { name: "description", content: loaderData?.article.description ?? "Practical insight from Taiwo Emmanuel." }, { property: "og:title", content: `${loaderData?.article.title ?? "Insight"} | Taiwo Emmanuel` }, { property: "og:description", content: loaderData?.article.description ?? "Practical insight from Taiwo Emmanuel." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: ArticlePage,
});

function ArticlePage() {
  const { article, content } = Route.useLoaderData();
  const related = ARTICLES.filter((item) => item.slug !== article.slug).slice(0, 3);
  return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="px-5 pb-24 pt-32 md:pt-40"><article className="mx-auto max-w-5xl">
    <Link to="/insights" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" aria-hidden="true" />Back to Insights</Link>
    <Reveal><header className="mt-10 max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{article.category}</p><h1 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">{article.title}</h1><div className="mt-5 flex flex-wrap items-center gap-4 text-sm text-muted-foreground"><span>{article.date}</span><span className="inline-flex items-center gap-1"><Clock3 className="size-4" aria-hidden="true" />{article.reading} read</span></div></header></Reveal>
    <Reveal delay={70}><div className="mt-10 overflow-hidden rounded-3xl border border-border bg-muted"><img src={article.image} alt="" className="aspect-[16/8] w-full object-cover" /></div></Reveal>
    <div className="mx-auto mt-12 max-w-3xl"><Reveal><p className="text-xl leading-8 text-foreground sm:text-2xl">{content.intro}</p></Reveal><div className="mt-10 space-y-10">{content.sections.map((section, index) => <Reveal key={section.heading} delay={index * 45}><section><h2 className="text-2xl font-bold sm:text-3xl">{section.heading}</h2><p className="mt-4 text-base leading-8 text-muted-foreground">{section.body}</p>{section.bullets && <ul className="mt-5 space-y-3">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-sm leading-6 text-muted-foreground"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" aria-hidden="true" />{bullet}</li>)}</ul>}</section></Reveal>)}</div></div>
    <Reveal delay={80}><section className="mt-16 border-t border-border pt-12"><div className="flex flex-col gap-4 rounded-2xl border border-border bg-card/60 p-7 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Ready to put the ideas into practice?</p><p className="mt-1 text-sm text-muted-foreground">Tell me what you want your website to achieve.</p></div><Link to="/contact" className="inline-flex w-fit items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>Start a Project <ArrowRight className="size-4" aria-hidden="true" /></Link></div></section></Reveal>
    <section className="mt-16 border-t border-border pt-12"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Keep reading</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">You may also like</h2></div><Link to="/insights" className="hidden items-center gap-2 text-sm font-semibold text-primary sm:inline-flex">All insights <ArrowRight className="size-4" aria-hidden="true" /></Link></div><div className="mt-7 grid gap-5 md:grid-cols-3">{related.map((item) => <article key={item.slug} className="overflow-hidden rounded-2xl border border-border bg-card/60"><Link to="/insights/$slug" params={{ slug: item.slug }} className="block overflow-hidden bg-muted"><img src={item.image} alt="" loading="lazy" className="aspect-[16/9] w-full object-cover transition-transform duration-500 hover:scale-[1.03]" /></Link><div className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{item.category}</p><h3 className="mt-2 font-semibold leading-tight"><Link to="/insights/$slug" params={{ slug: item.slug }} className="hover:text-primary">{item.title}</Link></h3><p className="mt-2 text-xs text-muted-foreground">{item.date} · {item.reading}</p></div></article>)}</div><Link to="/insights" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-primary sm:hidden">All insights <ArrowRight className="size-4" aria-hidden="true" /></Link></section>
  </article></main><SiteFooter /></div>;
}
