import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { Reveal } from "@/components/Reveal";
import { ARTICLES } from "@/routes/insights";

const CONTENT: Record<string, { intro: string; sections: [string, string][] }> = {
  "planning-a-business-website": { intro: "A strong website project usually starts before the first screen is designed. Define the business goal, audience, core pages and next action first.", sections: [["Start with the goal", "Decide what the website should help the business accomplish. This could be generating enquiries, explaining a service, supporting sales or giving an existing audience a clearer digital home."], ["Define the visitor journey", "List what a new visitor needs to understand quickly and what action should follow. This gives each important page a purpose rather than turning the site into a collection of disconnected screens."], ["Keep the structure maintainable", "A simple content structure makes future changes easier. Reusable project, service and article data can keep a growing website consistent without adding unnecessary complexity."]] },
  "conversion-focused-homepage": { intro: "A conversion-focused homepage is primarily an exercise in clarity. Visitors should not have to decode what a business does or where to go next.", sections: [["Make the first message specific", "The opening section should communicate the service or value clearly and give visitors an obvious next step."], ["Use hierarchy deliberately", "Headings, supporting copy, proof and calls to action should be visually ordered so the most important information is easy to scan."], ["Remove friction", "Keep navigation predictable, forms understandable and important actions available without forcing visitors through unnecessary steps."]] },
  "responsive-design-basics": { intro: "Responsive design means building an interface that adapts gracefully to different screens, input methods and available space.", sections: [["Design flexible systems", "Use fluid spacing, flexible grids and sensible breakpoints instead of assuming one fixed screen size."], ["Think about touch", "Mobile users need comfortable targets, readable text and interactions that do not depend on hover."], ["Test real layouts", "Check the experience at narrow phone widths, tablets and large displays. A responsive site should remain useful rather than simply remain intact."]] },
  "wordpress-maintenance": { intro: "A website is not finished simply because it has launched. A small maintenance routine can prevent avoidable problems from accumulating.", sections: [["Keep the software current", "Review WordPress core, themes and plugins regularly and update through a controlled process."], ["Protect the content", "Maintain reliable backups and verify that important forms and integrations still behave as expected after updates."], ["Review the visitor experience", "Periodically check key pages, links, forms, mobile layouts and loading behaviour rather than focusing only on the admin dashboard."]] },
  "ecommerce-product-pages": { intro: "Product pages need to answer buying questions clearly while keeping the path toward the next action simple.", sections: [["Prioritise product information", "Use clear titles, useful imagery, concise descriptions, pricing and important options in a hierarchy that is easy to scan."], ["Build confidence", "Make shipping, returns, availability and other relevant purchase information easy to find."], ["Keep the next action clear", "The purchase action should remain visually distinct and work comfortably on both touch and desktop interfaces."]] },
  "website-performance-basics": { intro: "Performance work is often most effective when it begins with simple, measurable improvements rather than unnecessary complexity.", sections: [["Start with images", "Oversized images can add significant weight. Use appropriately sized assets and modern delivery techniques where the project supports them."], ["Control JavaScript", "Load only what the page needs and avoid adding libraries or interactions without a clear user benefit."], ["Measure and iterate", "Use production-oriented checks to identify slow resources, rendering issues and opportunities for improvement, then verify the result after each meaningful change."]] },
};

export const Route = createFileRoute("/insights/$slug")({ loader: ({ params }) => { const article = ARTICLES.find((item) => item.slug === params.slug); const content = CONTENT[params.slug]; if (!article || !content) throw notFound(); return { article, content }; }, head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.article.title ?? "Insight"} | Taiwo Emmanuel` }, { name: "description", content: loaderData?.article.description ?? "Insight from Taiwo Emmanuel." }] }), component: ArticlePage });

function ArticlePage() { const { article, content } = Route.useLoaderData(); return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="px-5 pb-20 pt-32 md:pt-40"><article className="mx-auto max-w-4xl"><Link to="/insights" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Back to Insights</Link><Reveal><p className="mt-10 text-sm font-semibold uppercase tracking-[0.2em] text-primary">{article.category}</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">{article.title}</h1><p className="mt-6 text-lg leading-relaxed text-muted-foreground">{content.intro}</p><div className="mt-5 text-xs text-muted-foreground">{article.date} · {article.reading} read</div></Reveal><div className="mt-12 space-y-7">{content.sections.map(([heading, body], index) => <Reveal key={heading} delay={index * 70}><section className="rounded-2xl border border-border bg-card/50 p-6"><h2 className="text-xl font-semibold">{heading}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{body}</p></section></Reveal>)}</div><Link to="/contact" className="mt-10 inline-flex items-center gap-2 rounded-full px-6 py-3 text-sm font-semibold text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>Start a Project <ArrowRight className="size-4" /></Link></article></main><SiteFooter /></div>; }
